module.exports = {
  appendIfNotExists: require("./appendIfNotExists"),
  blendAt: require("./blendAt"),
  clipAt: require("./clipAt"),
  constrain: require("./constrain"),
  cpsmidi: require("./cpsmidi"),
  dbamp: require("./dbamp"),
  debounce: require("./debounce"),
  defaults: require("./defaults"),
  extend: require("./extend"),
  foldAt: require("./foldAt"),
  linexp: require("./linexp"),
  linlin: require("./linlin"),
  midicps: require("./midicps"),
  noop: require("./noop"),
  once: require("./once"),
  range: require("./range"),
  removeIfExists: require("./removeIfExists"),
  reverse: require("./reverse"),
  sample: require("./sample"),
  scramble: require("./scramble"),
  throttle: require("./throttle"),
  truncate: require("./truncate"),
  wrapAt: require("./wrapAt"),
};
