module.exports = {
  appendIfNotExists: require("./appendIfNotExists"),
  blendAt: require("./blendAt"),
  clamp: require("./clamp"),
  clipAt: require("./clipAt"),
  cpsmidi: require("./cpsmidi"),
  dbamp: require("./dbamp"),
  defaults: require("./defaults"),
  foldAt: require("./foldAt"),
  linexp: require("./linexp"),
  linlin: require("./linlin"),
  midicps: require("./midicps"),
  rand: require("./rand"),
  rand2: require("./rand2"),
  removeIfExists: require("./removeIfExists"),
  sample: require("./sample"),
  scramble: require("./scramble"),
  truncate: require("./truncate"),
  wrapAt: require("./wrapAt"),
};
